#!/usr/bin/env python3
"""Build nginx.conf from sites.json. One admin = frontend_port + backend_port."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ADMIN_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}$")


def _port(value, label: str) -> int:
    try:
        port = int(value or 0)
    except (TypeError, ValueError):
        port = 0
    if port < 1024 or port > 65535:
        raise SystemExit(f"{label} must be 1024–65535, got {value!r}")
    return port


def load_sites(path: Path) -> dict:
    data = json.loads(path.read_text())
    if not isinstance(data, dict):
        raise SystemExit("sites.json must be an object")
    sites = [s for s in data.get("sites") or [] if s.get("enabled", True)]
    if not sites:
        raise SystemExit("sites.json has no enabled sites")

    used = []
    admins = []
    for s in sites:
        admin = str(s.get("admin") or "").strip()
        if not ADMIN_RE.match(admin):
            raise SystemExit(f"invalid admin name: {admin!r}")
        frontend_port = _port(s.get("frontend_port"), f"{admin} frontend_port")
        backend_port = _port(s.get("backend_port"), f"{admin} backend_port")
        if frontend_port == backend_port:
            raise SystemExit(f"{admin}: frontend_port and backend_port must differ")
        for p, kind in ((frontend_port, "frontend_port"), (backend_port, "backend_port")):
            if p in used:
                raise SystemExit(f"duplicate {kind} {p}")
            used.append(p)
        if admin.lower() in admins:
            raise SystemExit(f"duplicate admin {admin}")
        admins.append(admin.lower())
        s["admin"] = admin
        s["frontend_port"] = frontend_port
        s["backend_port"] = backend_port
        s["domain"] = str(s.get("domain") or "").strip()
    data["sites"] = sites
    data["ip"] = str(data.get("ip") or "").strip() or "_"
    data["backend_bind"] = str(data.get("backend_bind") or "127.0.0.1").strip()
    return data


def proxy_block(bind: str, port: int, indent: str = "        ") -> str:
    upstream = f"http://{bind}:{port}"
    lines = [
        f"{indent}proxy_pass {upstream};",
        f"{indent}proxy_http_version 1.1;",
        f"{indent}proxy_set_header Host $host;",
        f"{indent}proxy_set_header X-Real-IP $remote_addr;",
        f"{indent}proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        f"{indent}proxy_set_header X-Forwarded-Proto $scheme;",
        f"{indent}proxy_set_header Connection \"\";",
        f"{indent}proxy_read_timeout 300s;",
        f"{indent}proxy_send_timeout 300s;",
    ]
    return "\n".join(lines)


def server_block(*, listen: str, server_name: str, web_root: str, bind: str, backend_port: int) -> str:
    loc = proxy_block(bind, backend_port)
    return f"""
server {{
    listen {listen};
    listen [::]:{listen};
    server_name {server_name};

    root {web_root};
    index index.html;
    client_max_body_size 50m;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location /api/ {{
{loc}
    }}

    location /files/ {{
{loc}
    }}

    location /static/ {{
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }}

    location / {{
        try_files $uri $uri/ /index.html;
    }}

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml image/svg+xml;
    gzip_min_length 1024;
}}
""".rstrip()


def render(data: dict, web_root: str) -> str:
    bind = data["backend_bind"]
    ip = data["ip"]
    parts = [
        "# Generated from deploy/sites.json — edit that file, then run:",
        "#   python3 deploy/render_nginx.py",
        "#   ./deploy/deploy.sh",
        "#",
        "# nginx listens on frontend_port (UI). /api and /files go to backend_port.",
        "# Do not edit this file by hand.",
        "",
        "gzip on;",
        "",
    ]
    for s in data["sites"]:
        admin = s["admin"]
        frontend_port = s["frontend_port"]
        backend_port = s["backend_port"]
        domain = s["domain"]
        parts.append(
            f"# --- {admin}  UI :{frontend_port}  API {bind}:{backend_port} ---"
        )
        names = ip if ip != "_" else "_"
        parts.append(
            server_block(
                listen=str(frontend_port),
                server_name=names,
                web_root=web_root,
                bind=bind,
                backend_port=backend_port,
            )
        )
        if domain:
            parts.append(
                server_block(
                    listen="80",
                    server_name=domain,
                    web_root=web_root,
                    bind=bind,
                    backend_port=backend_port,
                )
            )
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description="Render nginx.conf from sites.json")
    parser.add_argument("sites", nargs="?", default=str(here / "sites.json"))
    parser.add_argument("--web-root", default="")
    parser.add_argument("--out", default=str(here / "nginx.conf"))
    args = parser.parse_args()

    data = load_sites(Path(args.sites))
    web_root = args.web_root or data.get("web_root") or "/var/www/sockeye/frontend/build"
    text = render(data, web_root)
    Path(args.out).write_text(text)
    print(f"Wrote {args.out} ({len(data['sites'])} site(s))")
    for s in data["sites"]:
        extra = f"  domain={s['domain']}" if s["domain"] else "  (set domain later)"
        print(
            f"  {s['admin']}: UI http://{data['ip']}:{s['frontend_port']}/  "
            f"API {data['backend_bind']}:{s['backend_port']}{extra}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
